### ISSUE TITLE
Новые статусы

### ISSUE THREAD

**Issue by axd1x8a** [FSystem88/vk-covid#2]
Некоторые статусы убрали, а еще добавили новых.
Вот коды новых:
![image](https://user-images.githubusercontent.com/26704473/82369150-40cc0e80-9a1f-11ea-8e69-6122a9d917be.png)

**Comment by FSystem88** [comment]
Такая жизнь.

**Comment by axd1x8a** [comment]
Ну теперь ты об этом знаешь, дальше сам решай что делать
